name: Build, Test and Push Cellmaps Services to Dockerhub on Trigger
on:
    workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest 
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
        
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
              
            - name: Login to DockerHub
              uses: docker/login-action@v1 
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push Image
              run: |
                # as sibmanager has a dockerfile in it (this tries to build it, need to resolve this)
                for dockerfile in $(find ./services -name Dockerfile); do
                    dir_of_image=$(dirname $dockerfile)
                    image_name=$(basename $dir_of_image)
                    image_name=${image_name//\//-}
                    docker_image_name="${image_name//[^a-zA-Z0-9]/-}"
                    multiarch_image_name=1

                    if [[ $docker_image_name == "xtracit-dtma" ]] || [[ $docker_image_name == "xtracit-wsi" ]]; then
                    
                      echo "Building $docker_image_name"
                      docker buildx build --platform linux/arm64,linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/$docker_image_name:latest $dir_of_image --push || multiarch_image_name=0 && echo "Failed to build $docker_image_name"
                      
                      if [ $multiarch_image_name -ne 1 ]; then
                        echo "Previous command failed"
                        # as the build runner is running on amd64, we can try to build the image for amd64 only (as emulation through qemu is not working on the runner)
                        docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/$docker_image_name:latest $dir_of_image --push || echo "Also failed to build $docker_image_name for amd64 only"
                      fi

                    fi
                    
                done;
            
            - name: Upload log
              uses: actions/upload-artifact@v2
              with:
                name: build-log
                path: build.log





